# GitHub Secret Scanning Configuration
# This file configures custom patterns for GitHub's secret scanning feature

# Note: This is a placeholder configuration file. GitHub secret scanning
# is automatically enabled for public repositories and will detect:
# - API keys from major providers (OpenAI, Anthropic, AWS, etc.)
# - GitHub tokens
# - OAuth tokens
# - Database connection strings
# - Private keys

# For custom pattern detection beyond GitHub's built-in patterns,
# you would need GitHub Advanced Security (available for enterprise accounts)

# Default patterns detected by GitHub include:
# - OpenAI API keys
# - Anthropic API keys
# - Notion API tokens
# - Pinecone API keys
# - AWS credentials
# - And 200+ other secret types

# To enable push protection (preventing commits with secrets):
# 1. Go to repository Settings
# 2. Navigate to Security > Code security and analysis
# 3. Enable "Push protection"

# For more information:
# https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning
