target-version = "py311"
line-length = 100

[lint]
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "UP",  # pyupgrade
  "N",   # pep8-naming
  "S",   # flake8-bandit
  "T20", # flake8-print
  "SIM", # flake8-simplify
  "PIE", # flake8-pie
]
ignore = [
  "E501", # line too long, handled by black
  "B008", # do not perform function calls in argument defaults
  "C901", # too complex
  "S101", # use of assert in tests
  "T201", # print statements allowed in CLI
  "S311", # random usage is ok for non-crypto
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**/*" = ["S101", "ARG", "FBT"]
"main.py" = ["T201"]                  # Allow prints in CLI

[lint.isort]
force-single-line = false
lines-after-imports = 2
known-first-party = [
  "extract",
  "config",
  "llm_client",
  "rag",
  "notion",
  "embed",
  "pipeline",
]
