version: "3.8"

services:
  feedback-pipeline:
    build: .
    container_name: ai-feedback-pipeline
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - VECTOR_STORE=${VECTOR_STORE:-chromadb}
      - CHROMADB_HOST=${CHROMADB_HOST:-chromadb}
      - CHROMADB_PORT=${CHROMADB_PORT:-8000}
      - CHROMADB_PERSIST_DIRECTORY=/app/chroma_db
      - CONFIDENCE_THRESHOLD=${CONFIDENCE_THRESHOLD:-0.7}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env
    command: python server.py
    restart: unless-stopped
    depends_on:
      - redis
      - chromadb
    networks:
      - feedback-network

  # Optional: Redis for caching and task queuing
  redis:
    image: redis:7-alpine
    container_name: feedback-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - feedback-network

  # ChromaDB vector database
  chromadb:
    image: chromadb/chroma:latest
    container_name: feedback-chromadb
    ports:
      - "8001:8000" # Avoid port conflict with main app
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped
    networks:
      - feedback-network

  # Optional: Ollama for local LLMs
  ollama:
    image: ollama/ollama:latest
    container_name: feedback-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - feedback-network
    # Uncomment if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  chromadb_data:
  ollama_data:

networks:
  feedback-network:
    driver: bridge
